name: deploy-service
on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manually Deploy'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy SeeAndYouGo to Naver Cloud Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: 22
          script: |
            cd /root/SeeAndYouGoLegacy
            git pull
            cd backend/
            chmod 777 gradlew
            ./gradlew assemble
            cd ..
            docker compose build
            docker compose down
            docker compose up -d
            
